### ISSUE TITLE
GPI files

### ISSUE THREAD

**Issue by lpalbou** [geneontology/archive-reconstruction#2]
I don't see any GPI files in the SVN gene-associations/ but the SVN gpad-gpi/submission/ folder have GPI starting from around 2014/2015. I could complete our annotations/ folder with those when those GPIs are available. It may not be a big issue, but it would means that some of our archive (2012-2014) would not have any GPI while the rest (2015+) would have them.

I vote to keep those GPIs when they are available.

@pgaudet @cmungall

**Comment by lpalbou** [comment]
Additional notes: 

* most available GPIs are for goa_xxx. For MODs I have seen only mgi and xenbase

* we have multiple GPIs for MGI, it seems we were differentiating between the GPI (all genes), the GPI (annotated genes) and (???):
  * mgi.gpi.gz (7380kb)
  * mgi_association.gpi.gz (6965kb)
  * gene_association.mgi.gpi.gz (565kb)

**Comment by kltm** [comment]
How full is the GPI coverage? Is it all resources start having them at that time, or just partial?

I think there is a tension between uniformity and archive here. I think that generally it would be good to default towards uniformity and the currently contents/layout and have separate archives for things that may be useful but do not fit. (The big exception being the MySQL dumps, in my mind.)

**Comment by lpalbou** [comment]
@kltm see https://github.com/geneontology/archive-reconstruction/issues/1#issuecomment-666009763 .

**Comment by kltm** [comment]
@lpalbou Ah, understood.

In this case, as the GPIs are not central pipeline outputs, but only (submission) inputs; I don't think they would appear as "blessed" products in the final /annotations directory, but rather in /products/annotations (for better or worse). That said, it sounds like the GPIs only ever exist from GOA, MGI, and  Xenbase (correct me if I read that wrong). For the sake of uniformity, I think it might be best to drop them entirely rather than have partial coverage.

**Comment by lpalbou** [comment]
Either way, that would be easy to change with the mapping file. So let's wait for @pgaudet return for a final decision on this (and on the few other files that may or may not be interesting).

I think the technical part of this project is nearly finished. If not the CVS, getting the backup of archive.geneontology.org would be good if we want to include the mysql dumps.

Also, I would recommend that we use my S3 explorer for both current & release.geneontology.org (I remember there was a ticket somewhere to improve that). It's much cleaner.

**Comment by kltm** [comment]
Besides GPI, what other files are you thinking of? For the mysql dumps, we'll want to include at least a portion of them. assocdb from full would probably be sufficient; I'm not sure how much larger it would all get with doing lite and termdb...

I believe that the CVS will have older versions of data file--I'm not sure about how much was played into the SVN (just ontology?), so a little detective work/poking around may be necessary there.

I *was* wondering about S3 Explorer. Could you drop in a link so I could check it out? (There is also a ticket floating around with what Stuart did for SGD/AGR, but what you had looked pretty slick.)

**Comment by lpalbou** [comment]
S3 explorer: https://github.com/awslabs/aws-js-s3-explorer (it's also in the README of that project).

Example of other files:
* gp2protein and gp2rn: see https://github.com/geneontology/archive-reconstruction/issues/3
* enrichment-genesets: seems like a great starting point for our benchmark on enrichment - it's far from complete but it provides some list of genes and a few expected enriched terms (indicative of TP but not FP)
* docs: gpad & gaf file formats at different versions , go data workflow+ some schema to illustrate
* teaching_resources (ppt/pdf): there may be good things still or just to keep for history
* internal-reports: on ontology (2011-2012) & gp2protein
* meetings: various meetings 
* www: month-to-month dump of the website - could be some things to keep
* software: various perl scripts to work with obo and cvs for instance

Many of those are not per say to create a past release but could be useful to keep somewhere or aggregate with the google drive maybe.

**Comment by kltm** [comment]
Yeah--some of those could be of interest to various groups and maybe worth archiving separately. It might be worth binning them out to interested subgroups to see how/if they want to handle them.

Maybe once the CVS is inspected a little we can just make a checklist of the things to preserve in the "playback" archive (generally the things that map directly to current inputs/outputs) and the things to examine in a broader context (meetings, etc.) and figure out which groups/people might want them.

**Comment by pgaudet** [comment]
What should we do with gpi ?
should it go in the /annotations directory with the GPAD ?

@cmungall @kltm @vanaukenk

Thanks, Pascale

**Comment by pgaudet** [comment]
Discussing with @kltm 

What is confusing is that what is in this folder: 
http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gpad-gpi/submission/

is actually data from the sources - we never produced those until we had the current pipeline. Note that this concerns both gpad AND gpi files. 

SO - it's fine (great) to keep them, but it needs to be clear that they are coming directly from the source and that we have not processed them. Therefore @kltm proposes to put them in 
/products/annotations/*-src

**For example**
* goa_chicken.gpi.gz -> goa_chicken-src.gpi.gz
* goa_chicken.gpad.gz -> goa_chicken-src.gpad.gz

OK ? 

Thanks, Pascale

**Comment by lpalbou** [comment]
The few existing gpi and gpad were copied to product/annotations/*-src.gpi.gz or *-src.gpad.gz
