### ISSUE TITLE
Reconstruction from CVS

### ISSUE THREAD

**Issue by lpalbou** [geneontology/archive-reconstruction#7]
Original URL: http://cvsweb.geneontology.org/cgi-bin/cvsweb.cgi/go/

I propose to keep:
* [annotations](http://cvsweb.geneontology.org/cgi-bin/cvsweb.cgi/go/gene-associations/) - first trace in feb 2004 with sgd, then rgd and zfin in march 2004, then GeneDB, goa, mgi, wb, tair, jcvi and gramene in april 2004
* [submitted annotations](http://cvsweb.geneontology.org/cgi-bin/cvsweb.cgi/go/gene-associations/submission/)
* [external2go](http://cvsweb.geneontology.org/cgi-bin/cvsweb.cgi/go/external2go/) - seems always here but varies over time
* [GO_slims](http://cvsweb.geneontology.org/cgi-bin/cvsweb.cgi/go/GO_slims/) - from october 2004
* [ontology](http://cvsweb.geneontology.org/cgi-bin/cvsweb.cgi/go/ontology/) - only the obo file (start in March 2004)
* [gp2protein](http://cvsweb.geneontology.org/cgi-bin/cvsweb.cgi/go/gp2protein/ ) and [gp2rna](http://cvsweb.geneontology.org/cgi-bin/cvsweb.cgi/go/gp2rna/) - somewhere between 2005-2006 (see https://github.com/geneontology/archive-reconstruction/issues/3)

They will go in the appropriate folder in https://geneontology-tmp.s3.amazonaws.com/index.html#releases-full/ unless we go forward with a different folder hierarchy https://github.com/geneontology/archive-reconstruction/issues/1#issuecomment-680132384 . @kltm @pgaudet can we organize a call to discuss this ?

**Comment by kltm** [comment]
@lpalbou Absolutely, sounds good.

**Comment by lpalbou** [comment]
Example of monthly release produced with CVS:
https://geneontology-test.s3.amazonaws.com/2005-06-01/index.html

**Comment by pgaudet** [comment]
Will this be what the page looks like ? Or is this still under discussion ?

**Comment by lpalbou** [comment]
That’s what I designed for the moment but this is of course open to suggestions, anything to make it better is welcome. I showed it this morning to Paul during our group meeting and he thought this was pretty straightforward.

As a note: @kltm is planning to merge those releases with release.geneontology.org, so with the newer releases. If we do and if this link continues to be advertised on the go website yes I recommend at least this UI and message + documentation on the go site. There would be way to design a nicer more integrated download page on the website but this would take a bit more time and discussion.

**Comment by pgaudet** [comment]
It looks very different from the GO website. I would prefer we stick to the same look and feel (even if your new version is very nice).

**Comment by lpalbou** [comment]
Unsure what you mean: this page is for browsing the full archive and is much better in that regard than current & release.geneontology.org including in terms of "stick to the same look and feel". This is how this archive page looks to date:

![Screen Shot 2020-09-28 at 9 58 25 AM](https://user-images.githubusercontent.com/24249870/94463113-5261b780-0171-11eb-8309-5ea9521b0a50.png)

We can definitely add a footer and twitter / facebook / github links as on the go site and it would improve consistency, but I am not even sure we'll be using that page following last week discussions, so I didn't put more efforts into it.

If you meant for a download page within the GO site to replace http://current.geneontology.org/products/pages/downloads.html, we didn't prioritize it, but I do think it's a top priority, even higher than GO-CAMs as this is affecting everyone now.

**Comment by pgaudet** [comment]
Will not this page be integrated on the GO website ? Regardless, I propose that: 

- Is it possible to add the headers and footers ? 
- The fonts types and sizes, colors should be the same as on geneontology.org (the blue is darker on geneontology.org)
- I am not sure why we add the citation information, this is elsewhere on the GO website

Thanks, Pascale

**Comment by lpalbou** [comment]
> Will not this page be integrated on the GO website ?

No, this is just to replace the release.geneontology.org. We still need a proper download page for the GO site.

> Is it possible to add the headers and footers ?

Footer certainly; for the header, I didn't include the menus as this is not the GO site but a standalone quick access page to our files. In addition, if the menu changes on the GO site we would have to manually change it here otherwise we would end up with the same discrepancies as what we have with the external page http://current.geneontology.org/products/pages/downloads.html .

> The fonts types and sizes, colors should be the same as on geneontology.org (the blue is darker on geneontology.org)

Sure, ok

> I am not sure why we add the citation information, this is elsewhere on the GO website

See above, this is a standalone page outside the GO site and this section is just to give a very brief quick simple access to our files and what users should cite. http://geneontology.org/docs/go-citation-policy/ is a page full of text mixing citations for other aspects of GO (eg enrichment, Amigo, obo-edit)
