### ISSUE TITLE
Testing and polishing the GO archive

### ISSUE THREAD

**Issue by lpalbou** [geneontology/archive-reconstruction#8]
Considering the amount of data generated, this project would benefit from some additional testing and polishing.

Last version of the archive hosted here: https://geneontology-test.s3.amazonaws.com/index.html

- [x] decide if we remove releases prior to 2005. Pros: have most files consistent across all monthly releases; Cons: files slowly appear over time, eg obo in mid 2004 or mysql dumps present from 2002; it doesn't seem great to remove that history of the mysql dumps since it was continuous from 2002-2016, but one could argue 15 years of archive is sufficient
- [x] check all releases have ontology/ annotations/ products/
- [x] check all releases have at least 1 obo file and 1 gaf
- [x] maybe create a special release for 2011 when the SVN start being updated; the first revisions are not complete and CVS is sometime more complete; this would require special care
- [x] remove .svn/ folder (I saw some) and double check no CVS/ folder is present either
- [ ] create a documentation on the go site that will detail the current release folder hierarchy (start from the draft of go article) so that users can refer to that where to find these files
- [ ] add a README for the GO archive to mention major changes (eg introduction of go.obo in 2009; first gpad/gpi, etc) as well as the file formats
- [ ] @pgaudet to double check file names in different folders

Note about OBO files:
* for CVS, there was multiple OBO files (gene_ontology.obo, gene_ontology_1_0.obo, gene_ontology_1_2.obo, gene_ontology_ext.obo, gene_ontology-edit.obo, gene_ontology-write.obo, etc). gene_ontology.obo is in OBO v1 but has the advantage of being here from 2004 to 2018 (not in current release). I kept it for its consistency over all these releases. gene_ontology_ext.obo is actually the current go.obo that we provide; it starts around 2009 and is present in the release as "go.obo" file.

Note about JCVI annotations:
* they are in both CVS and SVN, starting 2011-04 (SVN), we only have a single GAF (I assume it's a merge of the 10s of GAFs they were providing); the jcvi.gaf.gz is also on the current releases but disappeared in 2019-11. Is that normal ? 

Additional notes:
* as of Sept 23, I am still uploading this new iteration of the GO archive (currently 2014-03), should be finished by tomorrow
* I still have to upload all the mysql dumps (2002-2016)

**Comment by pgaudet** [comment]
> the jcvi.gaf.gz is also on the current releases but disappeared in 2019-11. Is that normal ?

Yes - this is when GOA took over management of JCVI annotations.

**Comment by lpalbou** [comment]
Task: releases from 2011-11 -> 2012-08 use SVN but contains only the ontology. Specifically complete those releases with CVS data.

**Comment by lpalbou** [comment]
Close in favor of https://github.com/geneontology/archive-reconstruction/issues/9
